name: CFNew Auto Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest Pages.zip
        run: |
          curl -sL https://github.com/byJoey/cfnew/releases/latest/download/Pages.zip -o Pages.zip
          mkdir -p out
          unzip -o Pages.zip -d out

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy out --project-name=cfnew-ljsshd
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
